version: '3.8'

services:
  api:
    build:
      context: ../
      dockerfile: deployment/api/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ../../datasets:/app/datasets
